### PR TITLE
update ko translation on install.sh (app description)

### PR DESCRIPTION
**Pull request by jihopark**

### CODE REVIEW

**Comment by jihopark** [comment]
Hi sorry, I forgot to send this PR to the main repo. Please take a look

**Comment by jihopark** [comment]
Thank you for the fast response! Can you refresh the prod website to reflect this change? I still see the english translation.

**Comment by champierre** [comment]
My mistake. I forgot to update it. Now you can see the Korean translation at https://stretch3.github.io/.

**Comment by jihopark** [comment]
Thank you! confirmed that it is showing.

**Pull request merged**
