### PR TITLE
add traditional chinese translation

### PR DESCRIPTION
**Pull request by gasolin**
ported traditional Chinese translation from

https://github.com/estea8968/osep_web_serial/blob/master/node_modules/scratch-vm/src/extensions/scratch3_tm2scratch/index.js?fbclid=IwAR0qWd4e8i_Q3POKVktrafkNhEuOg_8MMkHfz7Rk4mGObjgNpemvLpfda20

`osep_web_serial` is an experimental project that we combine and localize several scratch extensions for elementary school students in Taiwan

https://github.com/estea8968/osep_web_serial

### CODE REVIEW

**Comment by gasolin** [comment]
@champierre please kindly review it

**Comment by champierre** [comment]
@gasolin Thank you very much for providing me with Traditional Chinese translation. Merged and deployed. BTW you may be interesed in helping with TMPose2Scratch https://github.com/champierre/tmpose2scratch :)

**Comment by gasolin** [comment]
@champierre thanks! will do :)

**Comment by gasolin** [comment]
@champierre here they are

https://github.com/champierre/tm2scratch/pull/35
https://github.com/champierre/ml2scratch/pull/40
https://github.com/champierre/posenet2scratch/pull/3

**Pull request merged**
